import type { HeaderName, NginxVisualState, RouteConfig, UpstreamConfig } from './nginxVisualConfig'

const SECURITY_HEADERS = [
  'add_header X-Frame-Options "SAMEORIGIN" always;',
  'add_header X-Content-Type-Options "nosniff" always;',
  'add_header Referrer-Policy "strict-origin-when-cross-origin" always;',
  'add_header X-XSS-Protection "1; mode=block" always;',
  'add_header Content-Security-Policy "default-src \'self\' https: data:; img-src \'self\' https: data: blob:; style-src \'self\' \'unsafe-inline\' https:; script-src \'self\' \'unsafe-inline\' https:; connect-src \'self\' https: wss:; media-src \'self\' https: data: blob:; frame-src \'self\' https: blob:; frame-ancestors \'self\';" always;',
]

const HSTS_HEADER =
  'add_header Strict-Transport-Security "max-age=31536000; includeSubDomains; preload" always;'

const buildProxyHeaders = (headers: HeaderName[]) =>
  headers.map((header) => {
    if (header === 'Host') return '        proxy_set_header Host $host;'
    if (header === 'X-Real-IP') return '        proxy_set_header X-Real-IP $remote_addr;'
    if (header === 'X-Forwarded-For')
      return '        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;'
    if (header === 'X-Forwarded-Proto') return '        proxy_set_header X-Forwarded-Proto $scheme;'
    if (header === 'Upgrade') return '        proxy_set_header Upgrade $http_upgrade;'
    return '        proxy_set_header Connection "upgrade";'
  })

const buildUpstream = (upstream: UpstreamConfig) => {
  const methodLine =
    upstream.method === 'round_robin'
      ? ''
      : upstream.method === 'least_conn'
      ? '    least_conn;'
      : upstream.method === 'ip_hash'
      ? '    ip_hash;'
      : '    random;'
  const serverLines = upstream.servers.map((s) => `    server ${s.host}:${s.port};`)
  return [
    `upstream ${upstream.name} {`,
    ...(methodLine ? [methodLine] : []),
    ...serverLines,
    '}',
  ].join('\n')
}

const buildStaticLocation = (route: RouteConfig) => {
  const lines = [`    location ${route.path} {`, `        alias ${route.alias || '/var/www/html/'};`]
  if (route.type === 'static-assets') {
    lines.push(`        try_files $uri $uri/ ${route.tryFiles || '=404'};`)
  } else {
    lines.push(`        try_files $uri $uri/ ${route.fallback || '/index.html'};`)
  }
  lines.push('        absolute_redirect off;', '    }')
  return lines.join('\n')
}

const buildProxyLocation = (route: RouteConfig, upstream: UpstreamConfig) => {
  const lines = [
    `    location ${route.path} {`,
    `        proxy_pass http://${upstream.name};`,
    '        proxy_http_version 1.1;',
    ...buildProxyHeaders(route.headers),
  ]
  if (route.timeouts) {
    lines.push(`        proxy_connect_timeout ${route.timeouts.connect}s;`)
    lines.push(`        proxy_read_timeout ${route.timeouts.read}s;`)
    lines.push(`        proxy_send_timeout ${route.timeouts.send}s;`)
  }
  if (route.proxyBuffering === false) lines.push('        proxy_buffering off;')
  lines.push('    }')
  return lines.join('\n')
}

// More specific paths come first (longer path = more specific)
const sortBySpecificity = (routes: RouteConfig[]): RouteConfig[] =>
  [...routes].sort((a, b) => b.path.length - a.path.length)

export const generateNginxConfig = (state: NginxVisualState) => {
  const domains = [state.domain.primary, ...state.domain.additional].join(' ')
  const activeRoutes = sortBySpecificity(state.routes.filter((r) => !r.disabled))

  const upstreamBlocks = state.upstreams.map(buildUpstream).join('\n\n')
  const routeBlocks = activeRoutes
    .map((route) => {
      if (route.type === 'proxy' || route.type === 'websocket') {
        const upstream = state.upstreams.find((u) => u.id === route.upstreamId)
        return upstream ? buildProxyLocation(route, upstream) : ''
      }
      return buildStaticLocation(route)
    })
    .filter(Boolean)
    .join('\n\n')

  const securityLines = state.https.securityHeadersEnabled ? [...SECURITY_HEADERS] : []
  if (state.https.hstsEnabled) securityLines.splice(4, 0, HSTS_HEADER)

  const listenSuffix = [
    state.https.sslEnabled ? ' ssl' : '',
    state.https.sslEnabled && state.https.http2Enabled ? ' http2' : '',
  ].join('')

  const parts = [
    '# Generated by ProvirPanel · Nginx Visual Manager',
    '',
    upstreamBlocks,
    '',
    'server {',
    `    listen ${state.http.port};`,
    `    server_name ${domains};`,
    state.http.redirectToHttps
      ? '    return 301 https://$host$request_uri;'
      : '    return 204;',
    '}',
    '',
    'server {',
    `    listen ${state.https.port}${listenSuffix};`,
    `    server_name ${domains};`,
    '',
    state.https.sslEnabled
      ? `    ssl_certificate ${state.https.certPath || `/etc/letsencrypt/live/${state.domain.primary}/fullchain.pem`};`
      : '',
    state.https.sslEnabled
      ? `    ssl_certificate_key ${state.https.keyPath || `/etc/letsencrypt/live/${state.domain.primary}/privkey.pem`};`
      : '',
    state.https.sslEnabled ? '    ssl_protocols TLSv1.2 TLSv1.3;' : '',
    state.https.sslEnabled ? '    ssl_ciphers HIGH:!aNULL:!MD5;' : '',
    state.https.sslEnabled ? '    ssl_prefer_server_ciphers on;' : '',
    '',
    state.https.serverTokensOff ? '    server_tokens off;' : '',
    ...securityLines.map((l) => `    ${l}`),
    `    client_max_body_size ${state.https.clientMaxBodySize};`,
    '',
    routeBlocks,
    '}',
    '',
  ]

  return parts
    .filter((line) => line !== '')
    .join('\n')
    .replace(/\n{3,}/g, '\n\n')
}
