import type { DomainNode, ServerNode, LocationNode, UpstreamNode } from '../types/nginxConfig'

export const generateUpstreamConfig = (upstream: UpstreamNode): string => {
  const servers = upstream.servers
    .map(
      (s) =>
        `  server ${s.host}:${s.port}${s.weight ? ` weight=${s.weight}` : ''}${s.backup ? ' backup' : ''}`,
    )
    .join('\n')

  return `upstream ${upstream.name} {
  ${upstream.method ? `# ${upstream.method}\n  ` : ''}${servers.split('\n').join('\n  ')}
}`
}

export const generateLocationConfig = (location: LocationNode): string => {
  let conf = `  location ${location.path} {\n`

  if (location.proxyPass) {
    conf += `    proxy_pass ${location.proxyPass};\n`
  }

  if (location.websocket) {
    conf += `    proxy_http_version 1.1;\n`
    conf += `    proxy_set_header Upgrade $http_upgrade;\n`
    conf += `    proxy_set_header Connection "upgrade";\n`
  }

  if (location.cache) {
    conf += `    proxy_cache_key "$scheme$request_method$host$request_uri";\n`
    conf += `    proxy_cache_valid 200 10m;\n`
    conf += `    add_header X-Cache-Status $upstream_cache_status;\n`
  }

  if (location.timeout) {
    conf += `    proxy_connect_timeout ${location.timeout}s;\n`
    conf += `    proxy_read_timeout ${location.timeout}s;\n`
    conf += `    proxy_send_timeout ${location.timeout}s;\n`
  }

  if (location.headers && Object.keys(location.headers).length > 0) {
    for (const [key, value] of Object.entries(location.headers)) {
      conf += `    add_header ${key} "${value}";\n`
    }
  }

  conf += `  }\n`
  return conf
}

export const generateServerConfig = (server: ServerNode): string => {
  let conf = `server {\n`
  conf += `  listen ${server.listenPort}${server.sslEnabled ? ' ssl' : ''};\n`
  conf += `  server_name ${server.serverName};\n\n`

  if (server.sslEnabled) {
    conf += `  ssl_certificate ${server.sslCert || '/etc/nginx/certs/cert.pem'};\n`
    conf += `  ssl_certificate_key ${server.sslKey || '/etc/nginx/certs/key.pem'};\n`
    conf += `  ssl_protocols TLSv1.2 TLSv1.3;\n`
    conf += `  ssl_ciphers HIGH:!aNULL:!MD5;\n\n`
  }

  if (server.upstreams && server.upstreams.length > 0) {
    for (const upstream of server.upstreams) {
      conf += `  ${generateUpstreamConfig(upstream).split('\n').join('\n  ')}\n\n`
    }
  }

  for (const location of server.locations) {
    conf += generateLocationConfig(location)
  }

  conf += `}\n`
  return conf
}

export const generateDomainConfig = (domain: DomainNode): string => {
  let conf = `# ──────────────────────────────────────────────────\n`
  conf += `# Domain: ${domain.name}\n`
  conf += `# ──────────────────────────────────────────────────\n\n`

  for (const server of domain.servers) {
    conf += generateServerConfig(server) + '\n'
  }

  return conf
}

export const generateNginxConf = (domains: DomainNode[]): string => {
  let conf = `# Generated Nginx Configuration\n`
  conf += `# DO NOT EDIT MANUALLY - Generated by Nginx Visual Editor\n\n`

  for (const domain of domains) {
    conf += generateDomainConfig(domain)
  }

  return conf
}
